defaults: &defaults
  registration_is_enabled: false
  count_of_articles_on_index_page: 3
  article_preview_sign_length: 1000
  articles_per_page: 10
  project_preview_sign_length: 150

  localized_domains:
    'bluepanel.org': en
    'bluepanel.de': de

development:
  <<: *defaults
  registration_is_enabled: true

test:
  <<: *defaults
  registration_is_enabled: true

production:
  <<: *defaults

